### ISSUE TITLE
I do not get it

### ISSUE THREAD

**Issue by forgithub45** [ibrahimaljalal/test_git#2]
what is this 1

**Comment by ibrahimaljalal** [comment]
what exactly

**Comment by ibrahimaljalal** [comment]
![_Git cheat sheet dark (FINAL)](https://github.com/ibrahimaljalal/test_git/assets/71209857/60861323-89a6-46c0-9a83-91875d497a46)

[atlassian-git-cheatsheet.pdf](https://github.com/ibrahimaljalal/test_git/files/11596298/atlassian-git-cheatsheet.pdf)

**Comment by ibrahimaljalal** [comment]
test

**Comment by ibrahimaljalal** [comment]
test

**Comment by ibrahimaljalal** [comment]
te

**Comment by ibrahimaljalal** [comment]
It is closed
